[[MLX]]
arch = "aarch64"
git-tree-sha1 = "23239d165193baa19becbe857db48e264a0ac8ab"
os = "macos"

    [[MLX.download]]
    sha256 = "0e78ff78190a53693732778e810f2fe0bdfc397a167e456e190dfc9a003bbda5"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.aarch64-apple-darwin.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "086fbe60c718ebddb911fd2a6109093859bd8a6f"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "787135835bda5e289ec05ca03c0c4e879763256b28333845f03098f09bcde6be"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.aarch64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3653d4c9b3b5294e74f4decc52ba824033f45a0a"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "c91c3a8955ffb81f7578d589d5f5b91bfee5ada947b7ad3fb8e2458f46aeeb9e"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.aarch64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "607115ff439b893ee3a486f1802d38383cbe5be7"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "b8f4ec147352673744f663129c583d6b28216dcd3fa0103ac47a75fd42c5288b"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.aarch64-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffb08d17135f55e100dbb3ee588edce0252894e4"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "c6bc8408672f9cf6487ad1fa544d0756c0091f031157bd68e64ce8e08b55bea2"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.aarch64-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "aarch64"
git-tree-sha1 = "b0e62f429a4a0f8591da142de3470efb0d469a48"
os = "freebsd"

    [[MLX.download]]
    sha256 = "06b94cc890c2863abf7107aacf11d17990bd508fce4af3ce61693a18fd211306"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.aarch64-unknown-freebsd.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b87a908e93d7863a40ef7afe398c9c07608c18e"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "26d9fccb3b53f5b6012b6a7f93fa9fbd8193387a817b0ee45668085a9d208886"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7aad788279500c28debafa550ea86773f5e586e8"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "b4e55e01062f43bf66e908daee991b565a7af0e05fbfeb3a3e7a46b671f1730c"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "930f905dca994fd3d9059188a96aa80cf1712b63"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "eaa9cf4bcce30944ca47b50fda46317f275c8b282820aa449d03b1fa2f064a90"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f9f424640924fa902d8a9284e4c7f7cc7d6f0ee"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "774a97a938a1c80b6c6a69a461ba1689080ad8ba412bea321af1c66da57e6494"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c4bb5a6e6b4f7a789aa23e0f0083c357d4b0aa7"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "1f1688dd32f0f59f3c3691452501f701d744b90122a99316a34d037c9b6f61d7"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea9129d8fd0a7da3b5b1dc3a98dc5dffa249c7ce"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "78a4a765414e526786d4dea7c6a98d293674c7a969f0cc51d7ae3836bd6f2dc6"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27738d444959a68b92897a77c434c8394ba08432"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "3919756baf6344b581d633514bb21ee98766d28662f80a823a6840050a4af590"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6fa1e216f7aaeee271a0da1ee3dfcf557d46e99"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "4794bca51696aa7870ff247d14a3e4c6d111651f08e9902ee76d14963448a5c0"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dae8344322684b033e344ad992c089c85213410d"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "03ec4dc735f287bb167531de92e2ded8f3bd9c261c6ef30f7f60275bc8edc362"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.i686-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "babb3ff13cc28e67b61f6e4eb3105d2398b10bb4"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "a40921ba7625c2faa61fabac9ace21e403f31ae8508a185ba506eb213aaa35d9"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.i686-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55e60b2bcc8c6616aba7d1e74cc0e61c87e759bc"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "e128eb0b952757b53d4b8fbf4fbf4fb70e97c1f60487dca4ae71a0c1b5c82202"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.i686-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e9608dd0b85b1737e6cb0a9e10bd44bec8fa95d"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "c3755e07c5956f7a3409a8e5ad5888fb4ba08b27b3710bb2f7fcee7828571750"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.i686-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2875721b771ec8bcf3d2a46b3c0342caf2e5e90"
os = "windows"

    [[MLX.download]]
    sha256 = "723bde18ddc9e3f427c2b4e04b808479e879a19d8ae6c960a2a59b8c8cded453"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.i686-w64-mingw32-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d852f9e4197d250b26380f869218b8774775ee9"
os = "windows"

    [[MLX.download]]
    sha256 = "9f9a5afb4cca542e164322da84883ea0e2f69eae1edec87dc2778e408a22a75e"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.i686-w64-mingw32-cxx11.tar.gz"
[[MLX]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0b4e0ef60c397199c0a7d7cb3c42f1bd822e98e"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "6a413df11685791bbab0f5bad7946d064f76c2c00888f5971c154890f9282da0"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b52119a29300e675c6732051dad7a3d3d9c6a0ea"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "3b1191aa00218a27bb329d521ddf7f49fe5d10f9c734bdc147092bd23e821339"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f840a006959b49e34e6c7a01cdf166659c8ec427"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "fdff1ea41c6f67fc69e5495b52334a08a0b1defece76af0b69f5213b09500f5e"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.riscv64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d8288ebb0183aa6f7fafecd17abeabb98013d1c"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "7e4c4d914dfe7f6b10f2d9a2bf03d54c9fbbe413f3bdea64c46cdc3fe6879650"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.riscv64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
git-tree-sha1 = "4ca68d72943654c05627d2834ac4ccf7ccb09111"
os = "macos"

    [[MLX.download]]
    sha256 = "d14280dd0b4230f4aaa830ef7bb71094bbd81f3d2ce1e8afacf0a25bafa0b946"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.x86_64-apple-darwin.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2f7c9fcbfa9bae09694299b6f978e7081c33371"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "4beb5ebd6dec405be816771af3bf7484084be975b6b9bd21e3b974ce95cfcfe1"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.x86_64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2ce5ef1083483d57da43e53b6967faa8722e733"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "1a0a2542ad885540b4078e43031063dd920e8cf61793497057b328e0d2fb89c9"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.x86_64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77bd0bcb8c3f50d0fac619abab5617a0525cc82f"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "a666001a56a654aefcdbf6c196cf371a324ea8d730424eab487b60c84c21ba12"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.x86_64-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "255e9c5e8360d4a906d5b989e908aad5beeae8e7"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "ff3fa30a4b7741737716f176efd4b46f73e061157bc8036308c46b6c07d50308"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.x86_64-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
git-tree-sha1 = "85b690818a9ae2faef84230f738f313381974c7a"
os = "freebsd"

    [[MLX.download]]
    sha256 = "c0fa5c585da3cd59aa09cf517a47ff8b7bf1978a0bc5393750af8da0bf449f77"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.x86_64-unknown-freebsd.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dab4635a0e4f22356640de87c3a8b3e49bee6c0e"
os = "windows"

    [[MLX.download]]
    sha256 = "22a4ec739a8326525d6bc22b891a65840ab45af2c6cc9f88c0352b28f0a3c192"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "124e7026f3e21db78127aee0137f5cf645a383be"
os = "windows"

    [[MLX.download]]
    sha256 = "4e87557225d96ec66d453b6ee1518c27ef39b773237ba910c8a7820016b0a180"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.0+0/MLX.v0.22.0.x86_64-w64-mingw32-cxx11.tar.gz"
