[[MLX]]
arch = "aarch64"
git-tree-sha1 = "056e175f88e6f64f33c1136bd5e949acbe2474e2"
os = "macos"

    [[MLX.download]]
    sha256 = "d794d327b36cce83ed783b8e2a33356e8964d9663fde829c8a44ac9fd06ed862"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.aarch64-apple-darwin.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "717eb90ae9d41d09d1aa69491de8bbc86103de07"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "b4ce73c4945f2893bd1ff9f87f81882b6e319c1fcae4494c15d7a4719ca40a73"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.aarch64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7d7d55ce217f61baf7396e131ef0c869a53a9b7"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "1682aca87a7b7ba56d7f5ea83d6a121732809298c006407ac6c47e61507b30a4"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.aarch64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f81d2e6fc518167c08fc598303fbd63bb8256ce"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "c7019e50520cad5969fb3ceca00cdc565e51b474acf4f3f9de920aeac3e5bbf6"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.aarch64-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56624e098f911c84f1b4d6dbdf80a17b19fb9879"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "2b63623f4e3c014b23b9bea933ef4b602f5662071aa6e82d87839653a4671955"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.aarch64-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "aarch64"
git-tree-sha1 = "c7e78876c6fc26c92423d52b7a90d3090dc055ab"
os = "freebsd"

    [[MLX.download]]
    sha256 = "b13abadb7bf4a5efce6f0ab4dfac0a3669cdd109bd10e8ec7fd807f96103c92f"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.aarch64-unknown-freebsd.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f17d2de424d9222033b7d2847844891dd128e574"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "119d92ab4bab3710d4f440b47be27c75cafe688f7f8b0074551027ea483fe7eb"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2fd7bd256b0f933aba63e50b078f93aaa86cab7"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "86705b4e13ccd31e6005f6b50e5cd77668cff729b8e58118576f3cd0e46c03cc"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41526cfdac2fab024afff9707da4923610d80edb"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "cf63fecaabe4dc9da20347c44e7d84a7b5fc3e52be40085b054243ccc1cd9bf8"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7471890a9ea63dfa8a8c42b920eb669e386ee55b"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "6fb57ca8ace0aee3c31d9af308cd1ad68d9cf35f63dcd7f9f81221bbafdc686a"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f29d56f1c7856c8c3aa63daa9333e63e1b96d164"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "f5ef8c7e190405c4480ea154940b2c46fa5cf914dd755c0f77f37334a21fddb6"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8eb82ad1d6789d357b7400630e0f80e26c9204f7"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "b9409bfec3ecb4be5199381c0f0a0f3c753a5f6af0c003c8bf992292fb1fd2fe"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "44fa12bc553f039a3c19052de9e7d3c933563731"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "7e32fcf3b091a8e9362a2797bd471a2e6e58c018005e5f98fd23256c234816bb"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6e937d8dba6a88d995ccfc956af1a2d27b14844"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "0e3f9cdd22d93ba877285a3bc3336d97ac73c0f200600de374013a8df30da17d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29a98e59f490c9af3795f97cd5c432ab3e3c2f10"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "b21184d877e13f9f9938a9d550e14bc8a76408af61a7689aac13ee3ecc245cc5"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.i686-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c1afa632a6e25aca2d1467b36550ad9ebffef29"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "6d702cfeb4e9f14b05973c45ea3d2134c97c57385cc42b19578522519f01b1d7"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.i686-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e694c0c45539bd14ee3edbbcb3e67117ab1f6c3b"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "2c61962195200a92c805a29554dc616ac4e576653be2edc349f2c6f5a4d5655c"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.i686-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd56599c73a148f47f1c5ce66bc398e24b5bd72b"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "e97d3f968d609acbdd52922c8bbbdd55f29220493cc4eea6fc9d862210508c1a"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.i686-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2409204538a5a86396e1437ac30a6afc44f5967d"
os = "windows"

    [[MLX.download]]
    sha256 = "22ec91a05b9acb47909d6bb29dea2cdd957bc39f6c361b2334e17727f61e372c"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.i686-w64-mingw32-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c0af2a81caea76a813bc4a3cd391cd9ad7c73a1"
os = "windows"

    [[MLX.download]]
    sha256 = "38a09f895d1bba16fe5de5ec1ee8101520672481c772b500dbc7bd32ed9f0bdb"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.i686-w64-mingw32-cxx11.tar.gz"
[[MLX]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "711770b71d808fe5a333835ae2f0284a8e7f280b"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "6c8a0feef68d9677618438d57d8511f23c913e7a877213b38ee1d87cd1ae2398"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f45436230a8523b76a981369fa7d225b7ebf8365"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "7a1b603e4fd65253a4622d7866615215f9aba59d11783fba10b4c5fec177b75c"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
git-tree-sha1 = "1d86edcf5036cff55e6c65afed9ee0d433a56d54"
os = "macos"

    [[MLX.download]]
    sha256 = "6e269c699ba06b81e160d277807950795be488005a4f8198bcecf8e2a6ef772e"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.x86_64-apple-darwin.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf5b1cf34a440a971581b31a3190deafb17ca9df"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "c7c8a9ae69064d730d0513915b13a1df80841f975bec0823d5cf0325881b724a"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.x86_64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f14c60b2300561f9c487e4cfce034cff0e0fe15"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "89d08aa0e5d872c82d4c8eb1b166ad44001c8e422065aef7af17e560a150c466"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.x86_64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13ddc81bbd6d812367035c0471792132c868e618"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "7fd3edfb07d1d6162c015439664c9b33ed173cb559bf815d503e58d63ea07450"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.x86_64-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd7ca9f8f86ff6423819247389516060bfe90e7c"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "9f099194fe119734f1cb59d2d6b1363d433aa947b7e908506191c980c347fdab"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.x86_64-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
git-tree-sha1 = "f7c620504f90c687673410c4d45578f10bb4d87a"
os = "freebsd"

    [[MLX.download]]
    sha256 = "93ab1c19764e285e7f4b85f3922776aa2d760e4708ea8b645ef1ca0675e24d6b"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.x86_64-unknown-freebsd.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d50263811a7d6022ddfa8cf9a9c0a8b09b73d49b"
os = "windows"

    [[MLX.download]]
    sha256 = "4ce7f86677fc115cc08079baa89648775c7d802a1cab317802b1546963590ef5"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2488507a1b0e163a7cbc842116d18584d4e4f708"
os = "windows"

    [[MLX.download]]
    sha256 = "ebdec294faf8c8c2a77dc9e3633d9dc9c6da004c00ca38755bda06e807eb6f2d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.0+0/MLX.v0.21.0.x86_64-w64-mingw32-cxx11.tar.gz"
