[[MLX]]
arch = "aarch64"
git-tree-sha1 = "c73de554595ede8fb4a0ec0010cc60a8021fe54b"
os = "macos"

    [[MLX.download]]
    sha256 = "27736b70f96f44dfa4fc8ad3e0dbd076d173eac91c6e2dcbfa7173558c5d36db"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.aarch64-apple-darwin.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e85852ffb62d31d37f9134b52def46b480107b76"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "4cbfdc8ee5233900a18d6f3e925406d4c7ed072cdc118a5ff1e1322e85dc7a01"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.aarch64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b5713bccda4c1778fea0afc8117717eb6d0f40d"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "db011f72b3f60b028d4b4993b069a1c9d9edb5f34a926322803d83f6796744e0"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.aarch64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8461e08c762445d5102a8c81fc0f964eed23490f"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "50a319eacde815e9e3730fe1cc4646948000f27b0260734c09c5f1ac1a06fc4e"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.aarch64-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7664b7e7f1f75b2fb4895b5280b247fb54101751"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "dd09b4345fe294fdc6b5d9e67639dad1360a21447a9f2e157c4cb53e33f24b41"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.aarch64-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2ba863535a57dfadd67896229ceda5cccb1ea29"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "fe547fd20a09fb4ec2000fc45150a105cf8e3dee413c2ed1403564869715d494"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e8b5dbc30ec174d342cfa73e7f52c50c5a6e2b4"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "694ba203de81afab2f20da2e30cca7b7427a54bd887b5518429defb1b9e4d408"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c949ad7e1ffb753acd086288e719ea5707a76c9"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "eb64f35937c9fddd3564c0e741e1a9c7162519b92161aa3821cb913df310ae5c"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20bf00981fc2f7e17ef64d1ce8f6f22041cc419c"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "d03ff34eeee15b82df9dfda8d5cb4fc8191f0976b15554684c4aef8c4ac2f795"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3be3ad76772452c2a406b8f71195231f8b863603"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "d78d04a20e476812192cb9f4608a32c37046c69b623f2b2376cdfe0168983d7d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e798358bae8b57602ebfb404c33d82afc2c375a"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "fd4c9429dd713571e6eb16076054fd01aefaf1f8bfee6ed1db6a96623b9ea452"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a83042d66feb8964ac2e3b73bd186c4cf82fafda"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "75371a040ca869481e16172944fc02018706f5cde88a2ad9fd6d8599ec49d2d6"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f9922fa2158c902ccb933d30a6888bc5aba3fcc"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "3e8e8e149098b16c26e83f3aa73b41421f90a52eae4ba2c68c8b6260ac5e2f58"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7857df679868533dfd8cb686fb0c35d83c3936bb"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "1b0cf0884bb076c7d1f4e3068b0cd8f24dd7846e18822524bfcb5b997cc69f47"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.i686-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b62248a7e8c80301f66da31ac5b08f7b65fb7894"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "e99bff78b747ba4cd528f00d2bcfbab2b56f7c9fa69cce80e96cfa286290a97d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.i686-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5ab8b46adf2a3a53264202f11199d11d09bf9c6"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "ca2b91941216bbda639d50cb11084bd196a7649d9d77b4fefb88a79ba915410f"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.i686-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ccb99edbb382226ae5c878128680fa0b9ce39b8"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "e227807854b4062d2d218cf80d996576f9ac080dd4bb9f2c7650c7ed139eccb8"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.i686-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39ba200b9f5087ee78ed0dcafe5cefcd955b465d"
os = "windows"

    [[MLX.download]]
    sha256 = "e48c6ebe50182af10de2a3c7036d7398d573eea9a1c9fc541390277707b2c93d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.i686-w64-mingw32-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc08e4421665e8516333c989ada209f9469cc3b1"
os = "windows"

    [[MLX.download]]
    sha256 = "e1161ec6a3794f0488373d824a2beb306af953e8e6bc1c0f60d226b3c742e2c8"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.i686-w64-mingw32-cxx11.tar.gz"
[[MLX]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18533771f3d4c18003df65ffa616da3954ce089f"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "a3bfea73003440353df5dd91fdefe5ff137954cd58fd2004169b43a5632eff4d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e18ec255d7604ca9efcc35cc4976bcfa1a0fedc"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "29adef70301de0c0c66d124d06124cea3db094ddf9ad8f540abef14e6329b863"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
git-tree-sha1 = "5188ef0884df85ca9f32fd1673e488b76516786b"
os = "macos"

    [[MLX.download]]
    sha256 = "ad05d38a3e9f320e4bf3e0b90a4f5f9137e39e20aa6b5b680c80b64643fc9931"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.x86_64-apple-darwin.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d1027133ca4b766684dae90320ca60ef4f7001c"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "5bb6baf0667016b176316915cb4b960e020fe10236089974d2d4c4aed92749a0"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.x86_64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c39473a3e6cc085e48b7cfd7aa297a2e74e79c1d"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "ec2294c743f2910d277656fa40385c5d900e751d5bae7d8769c5c733b56538c7"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.x86_64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3667e748cb7e917c643ce0b00f8d4c75caa92be"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "cd9ff2218d8a1daaeaa31e6b860e9ae204da67eaa0ace117193a0ad13b8d40a8"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.x86_64-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a72a0943ac6b1eb8ba85b4fe76bf0d01d946b76f"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "46bb40ad5d1e3e9254fa8bd799766666224bb6f49370e2c14c9d0055b5e6bccc"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.x86_64-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b276fd98b2cc9a02550ecf70f3ebd178ab2e292"
os = "windows"

    [[MLX.download]]
    sha256 = "27c9b665246a18364fdd127100a8dcd229f44d6e47aa1bc931f40586b84ca70a"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70b1d6eb8ca9b491b9e4d3b7f4dac9254b58d163"
os = "windows"

    [[MLX.download]]
    sha256 = "20f18e94329f44e49a4c0e74bf4d33e53820cfd8f912936eff41ed1d3e34ff72"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.20.0+0/MLX.v0.20.0.x86_64-w64-mingw32-cxx11.tar.gz"
