[[MLX]]
arch = "aarch64"
git-tree-sha1 = "046ae0b5d408c65cf5a1632c12ab7c2b56f6c7fb"
os = "macos"

    [[MLX.download]]
    sha256 = "88ce4baa8bbae0b0d5437990fa50c85f441fe0eec3957122f621a599116aa100"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.aarch64-apple-darwin.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "172673c744978e5924d923ec8e0aa3fc510ac2ac"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "699c4c5b946d9cc6036330c8239e31379fa306e1b146b591c9ff91e374998958"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.aarch64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ae54acf2e75d4aa2b2a15d98141fed04f0bcf02"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "56ffb3bb03e74c874c612ef52801bc6dc89cb09bf35e7c26a139ee5415efcca5"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67fd1c3c53eade26794e0c9aaa687d606bec07a9"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "4248ce159a74bd990aad9d18b2edac53f93534deab9a48d5cabc6ac4e51426a5"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.aarch64-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd5acdc368ae396c10d33b63f5fbff7627bdd5e5"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "2e43b16369ed046f9dc3e7b17ef82a8980884a8ac1e4436cbcc5a9a8b2ddb27e"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.aarch64-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "aarch64"
git-tree-sha1 = "153de189148dd6f463c17e884a51c2221cf3e2d1"
os = "freebsd"

    [[MLX.download]]
    sha256 = "70a62694d16c0600793d4e9c4225e5ccca303a2aa922c48f893f967a88ff8498"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.aarch64-unknown-freebsd.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "acbd9b939cdc76bf93eea3753a926e621f54ea84"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "0a42fde59d1e5aee2962cd92b1477811512498cb58eb601e12963a7b8915ae01"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a98200ab3295bcc66638b979decf94dd3aabef1"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "42771fd84572636db0302f18d928169ba87e6768469d0dfd97955198500d972b"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e28806cc0cdfdaa709cbcd6fc7043fff342d7a9"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "a7238e6dda4ae13cf86904e643befd787bdb0f242c195625a799c51010c717a5"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67da4bf957abb4ece8781d51f9868ecb94cb2184"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "49f0173bafa165329363f74cbe37b48f8fee8254ed300063290c8cb15a425f06"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ddc3826359bc936ef52585f7673767bec0ecb2c"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "cbb0f7e95029fc3bcb99bb5df8be615fdaffdfdb341a8a7edc1b3f9a5c3cb66f"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d8fae345520ddad3d6efb5f25a781dffb39a42c"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "c647157115b7d6ba140274ade9f319e89c85d2e9de660725e09eddf85c6d3d95"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "acdd7b7ee5012b99ffd3e3291a67acda2f01205e"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "403b67d3b00b1a608d2eed1eed30161adf61a58f9f746a561cf6b851f1e23dc0"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "725248d31fcf10243cb4cc91c52e974a7a6f2215"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "d994f2438097c9c68fe07e9d71841193ec3fd0dfee79207f80ffaabf43721302"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "30f2aaf916e944ce878411cef2310669e19cb717"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "4dc9b1768968e4266b37ea6526ca7b4a0d4bd4d6a2af2be8395aab4e417d506e"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.i686-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2fc46035680aa2875362294bc3f4475ef264acfd"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "590bb3ee6e3c239c2ebac5afe553e9bd3b0d43c08ecdef15f7d7d28e54696a5a"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.i686-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a56375d0d536ed7fb47b387951cc19765f8ebe1"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "d025bcd7429e128c150e43ada4ac3c897e24fed8aea536bb3ca03455b84ca88a"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.i686-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50ad8a68d9b356a7face0806ff842f08e791dc7f"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "b5325dc858275ab42b5e6001e9e33bd63439a27b97de4b1b9856b19859be4823"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.i686-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1491a67ed5ab01ace51919beef80c96d396b9d85"
os = "windows"

    [[MLX.download]]
    sha256 = "b0691714088539fa2101b3e26aa4335594dd827e938d6cb3355fb437cd35c723"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.i686-w64-mingw32-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2129d2b3f7e0c12c076be58ba5251a244bcd8edf"
os = "windows"

    [[MLX.download]]
    sha256 = "0bde450d2d54c28223f77c2917d89bdb0b1eb88bd6f02367ca723bcb57eb66fa"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.i686-w64-mingw32-cxx11.tar.gz"
[[MLX]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3e83ab4335c8baccfce9978d1c07f3c979506d8"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "c1788d5d9997da7756839898fe59b3275866db16ae1c1ca515049030a54e4c7a"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13c2fd64403e056cbde7f890f3d3cc780ab2a17c"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "52628f647e461c37e57b1caf69a01982d1bc8551fb46ef8ac4765f4c4e088c8c"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
git-tree-sha1 = "7efdd11f63c313597d88cdff6a983bd60274c76d"
os = "macos"

    [[MLX.download]]
    sha256 = "6b4ea5d92585e44a63c4b07a2125807850d55038b1ac58e9853442cfc529e739"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.x86_64-apple-darwin.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e759ef14446320684c1aaf4ab5bed51945459dc6"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "e6097d71795ceb0b8e6accb898590a890c80d3ab7b5bde4dab777e702115671d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.x86_64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67148bf15be4ec14ea50485f240aa753d74c4c93"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "56cfe03586b2df6c9bc9ec8767a3ef358a3569a19e3a5d0d5b8e7733635f86b3"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b36d15be4d76594d225f32c26ca097882ead9f9"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "78f03bbcd6c724a8d0d001ac371601ef61f2e653eec27a1dcac3c8391813fdff"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.x86_64-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce73bbb8c8a44512a612f24ef5ba38002a5981f5"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "4f54f59fba48a8a372a586a908e9d0fe07bc4e43e0da34c7f8c00efc5d6a477f"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.x86_64-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
git-tree-sha1 = "3d62ece837755e3117a2372484379ef8c0488f6e"
os = "freebsd"

    [[MLX.download]]
    sha256 = "7c243b6ffa2519b4041f729afb791775c25430ce8155029d75d7dbbf9fe2124c"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.x86_64-unknown-freebsd.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97a49556c817b5c03b5957f3bdb919cc089cc77b"
os = "windows"

    [[MLX.download]]
    sha256 = "80060e0ce5cb0e550ad50e7e74ff097ca1fab805e8634eaebdce17cf76a99a0b"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfac1a478008712a202d779e6bde074ef399f201"
os = "windows"

    [[MLX.download]]
    sha256 = "d419e949c3a3dcf1ae40c12f23974418da5df9a1172dc9e4c22f3f7f42a351a2"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.21.1+0/MLX.v0.21.1.x86_64-w64-mingw32-cxx11.tar.gz"
