[[MLX]]
arch = "aarch64"
git-tree-sha1 = "e04320d7a704d2b8052afe6942364ff54baa8868"
os = "macos"

    [[MLX.download]]
    sha256 = "4e42eef8705d6e92c2cb973aed047abd1746b4bef3ec4a1a7e1e34fd49620848"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.aarch64-apple-darwin.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e775a7375fa67438d08fe995451514020ffc6a5d"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "f2b9a56f17e253c383753158eb1077e7ae2ffb15390696c81832cfdca5865ae7"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.aarch64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d762c3a149258db3ca01c68a952785b73826be52"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "4b432914ceac9b76e146ce3ae16a0090febc743d264dc93499ac329ca69d50ef"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.aarch64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d6e0c54ff4edf7d2e4e0b70430986beddabf174"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "ecfd090c168b4a9beb2279faf97dcba6b2f595d9cd09f19f092da38d65f9f611"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.aarch64-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39be74e8f0062bc0fdfd534779dcd22761177ccc"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "40b35e56199762eb253896e33013fbf5e6a38d74153523910240f1527e1bd409"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.aarch64-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "aarch64"
git-tree-sha1 = "d4a95df18e44f3af2b093e379fe8ca841b20ef10"
os = "freebsd"

    [[MLX.download]]
    sha256 = "5452b2fe0c31f75a23c441317f10fb4fac2d2abba6e34e459e4faa86aeef6f86"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.aarch64-unknown-freebsd.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2dfe6bac45160d62123a33a404b9ed80c62dd162"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "8ff23705fa27e535dfe4609915d659c19971c05cb6a9deb524f45cb151c96b4d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e615a35a2ab253bc0f487c1d5e65137ad78a8fee"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "394ce0ee5beddd8415c6d1ab9ce4a1bbda072379e215b49f27e43febf396b5c2"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87cc984c6302a7c7b1c27600dfa668e1adf842d4"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "135a004448596388db4d6fde1b915cafaef190e17521162e50f5991a71227a92"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ec8296bd9a5702743dc1d9ba48f5d90d5535515"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "f2fc28c2d4302809e881188acac1c47c3c1d9a283d249e4e410e7cd43d5f179e"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e83f8d9cb06dfb6ec9ac741338c080b90e28eeb4"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "a4e6b4dca2ed7a3b6191830d20b4f4de9624623b2e9f91897b3ada9bd21d80e9"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7597966d5f197fd98f5b4ae3f9d2a2c327ee43ad"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "8eae2fa836c9068ab930ac34f2bcd7feb2e3cccb5086cd604a63b1e00a93a5a8"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "054644346ac3c87946c3c8eeb9936afc394baa84"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "0672a6af1794bfd02af5d8a4e79d4c68fb5f3acd2cd7f7439b6b8d9dabb2bc51"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "066f9ec9e67bd1719da977092e1a39074a4d531d"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "88afac13a69f0f7bab656dd4f4424896a9825ed56436afdbf1009225d4cffb72"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2eea6b2ed4b7415684b826b6092642f310fd5c88"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "8dc9270a54059bfdb08516e7a61b6d59d3f0381c6d938e68fb9438ae173dab1d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.i686-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37cb6dc44dc7e8a79e1c2a2633271c4cbd91371d"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "1eb05b6a3b04b06c07d33447aa7e1329f7e9ee9cd7b78c4597c9b181f81f7282"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.i686-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cd74f31409f1c5ff724e3729a0fb09bf24e5d59"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "b5ac100195fcaf07f378bbdd22a23c715f56c9c017e552e9c794689612a46721"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.i686-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fcf7ab546201a111b34baffa7b106276b1c9cbc"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "120494bad787de0c0f8f9f27881ba660448689160a5c695f618cb82a24be70f3"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.i686-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3e1b4cd7fc3792bc5e186859989c80521fd189f8"
os = "windows"

    [[MLX.download]]
    sha256 = "9deaf21d5be7935deaa3d062f8a2dac55f6dbdbe155c765e9f61fd8d344921a0"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.i686-w64-mingw32-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f1aa8cabf775a2f8a357da8c8218ce0c016d7aa"
os = "windows"

    [[MLX.download]]
    sha256 = "ef937f098ff9440ffaaa883f7f9e1871949b21472c52a196459806cd4854e509"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.i686-w64-mingw32-cxx11.tar.gz"
[[MLX]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d604c749a291309614732781c5395b10321b588"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "a3e25baaa0f0d93e73a64b8cb5a5c68e77dccbb615948f44d7b6a0b2def7ac54"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0a6532a81add416f8b8d1a3c381ac95fc4d05bf"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "84bd13daf3f94709e748484b1ed7168259314711050c234819723764a43224f0"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80bed46fc433b0343697edebc818d37bdeb11ced"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "69a4b78ed485860506f4dbe727cb0dd516e6870a1494c67ecbfbfd69946b6829"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.riscv64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6c0f19186766ea03e2cb7d14c7fc31d5c8f1fad"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "413bf315ff448c12d2ffc8cb86261c162bd176d977a1127e6fc04b293ee2f589"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.riscv64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
git-tree-sha1 = "c0c886399412cf4632b7e8f18cb00ffbd089e078"
os = "macos"

    [[MLX.download]]
    sha256 = "a98d914812b168232700d4705cfe3f8b9d6a8e8cff7c1e792ac7cc12424e9521"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.x86_64-apple-darwin.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b88c17651b71cff0351542aeaa27d31faf9c676c"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "6fd7b64ce5af220881cb8de01fd72d674f85fe6c6d2e436bb588077b48112ff8"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.x86_64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3989710392a6989bb2bae6da06f06dc1d10138db"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "2e45bacd8a745fac3a019e4d9411b95055523836651cddc7b1ec8d800e857ce7"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.x86_64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf0044f1fa184f6db7e1bcd8aac97672a9586bd7"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "2743c03cb22af8b9d39f51727964fcdd1c769b6a48882d7a1b5d38b233eede13"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.x86_64-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "744570cd440b703fc6feb4071b2458f668dcb5e9"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "44249119525c6784131fa05821ebff5f2857933aafcf2ee61648b227b0804e8a"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.x86_64-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
git-tree-sha1 = "cc5975d06fbc39f0506879f2fa8c418ce3450b35"
os = "freebsd"

    [[MLX.download]]
    sha256 = "fdd8227481f3245ae294d8272d56065df4b5f670a6de8c1ad125635ff1f1a8be"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.x86_64-unknown-freebsd.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5098183684539994732bf2e68556f2297650b8d4"
os = "windows"

    [[MLX.download]]
    sha256 = "3642853393f30545eb3f514dd319ca4844cfa49e2a96936e68514c3f52a8b9d4"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d0921a3c65badc7bc422c469fdeaf537460ebd8"
os = "windows"

    [[MLX.download]]
    sha256 = "9e1425a101049c0cf85c8307eb44008cf85ccfbf515f1321cad80925a0877082"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.24.0+0/MLX.v0.24.0.x86_64-w64-mingw32-cxx11.tar.gz"
