[[MLX]]
arch = "aarch64"
git-tree-sha1 = "657bd6139f6caafacfa72e3602ecdc5c086b1b2e"
os = "macos"

    [[MLX.download]]
    sha256 = "a20bfd790883ba7bf660d220c49bdce09914e3914fa39fad8b9f2a2262e20d1b"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.aarch64-apple-darwin.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27382ba5bf3b454e3fe6388c8f1030723e48dcac"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "a8434bda5536ebe7cf675ec751c52e216d1766343cb3470e3961f5d29aa06c52"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.aarch64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c34c0df1ce46315c5f41273452b111f8a8e0d7c1"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "21687ada62040c1f451d3f8faa694d155406d1e07c892139fb61a9c5b1c74fca"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c22c47e65916b87f2a91d23df0f19657a40cb190"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "a415cd0f2ce7040016acdab4a837cdaae1bb90a7e19a3dc605625516746a3bef"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.aarch64-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d747643593125406ebbd7e5c2c4db9c5975b059"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "e04850dbaed6970a1ea120ec1ba1d4c57ca95befd78e838bebffaee3f891774f"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.aarch64-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "aarch64"
git-tree-sha1 = "092c417f6e9010b4a512b3b7f5db45aaf156dfba"
os = "freebsd"

    [[MLX.download]]
    sha256 = "3b2a2f998263cf7c21dac225b66a671ef3ff71e241f92c3cdaabdb84a8f0b077"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.aarch64-unknown-freebsd.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "475b6792a417981d3395c0cca5a764c78143cc6a"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "e4533425bea7ce90f53685f39f18f59ffda36dac82dfe7d7781b769bf16e161e"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8008d0ac40e38e1d75c5313ca1eee4ebfed10813"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "dd1b6da04fb135876f89f55bee2cd0b4f75b48c30d25c6a158de6982d4637ec2"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cc01973d1989e46ef73e91b226b142b3399b11b"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "555dc9a39fbaa2b6568af9d9b6fc71cc0797da6aead0b028388b53b721f00f22"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f5d3071984e8a03d69593f5c6c6dd4ab271f67a"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "2f6d57c135127a4e60603555fa135e50a4cc53048bbdb7e5bdbb12fc05797350"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdd0a0008b281470924c97fd4f9b71c6552eaa1a"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "26951d153e4f81c0c690bacb5af2197864264bfc7f3b322eb9affd9a3710fc03"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01c165b0aeeb748a42d93e0d96abb2df059278d8"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "f81bd9a04aace3557bb9123b2329f1c9f4e6cee475f2ec040480f5b6b7f565fb"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42a40c523e6a25190959d7034751b69cb2da6a19"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "7654d4377befb9fb205b7e7653477d1bf59f21ea93c2f6c66697c6e3fce26ba6"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c28d2c0a2230fe53c40470b957c8dc0117f975f1"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "4de0c8436a22df1984630afe16419a73ae4fbc97276d288ebb1070c944baa605"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "428f47b937ffe3e7443ed6b5bf4b12c515294cb8"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "6a9501cafd881758dcd64b05654ca9ad334d49fdd4c6e709e4bdc377efd26fd8"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.i686-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2010e28efac37e077dc02e1f84750a136add561c"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "b571d9ee0025177b2877e547fbb676b39507aada4f8da62423c76e59ac3cc6f2"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.i686-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b9c49434d47e2ac5562da2fbb7fd0840de647aa"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "148f150fe4a16f0064a681362c2d0e05d97a58acff35eb6ee9b547508a2fa733"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.i686-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b88a45a15f66416d24c40aa145988a71b4f9435"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "248626c79942ba48d3d0b3db6d45a58dfec4be002ca4ddc77723533a0c2b537f"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.i686-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "01a0456565bb64058016721efd3a0bd7224cf2d3"
os = "windows"

    [[MLX.download]]
    sha256 = "62e25e1ffe8c82cb3e5203fbdde8da64b86c7b45424f66926efd40b334f782ae"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.i686-w64-mingw32-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a4a179f71c3b35f37f42070284d6aecdf0ba00a"
os = "windows"

    [[MLX.download]]
    sha256 = "5ac4f45f18015d36df8b70d3a97373314216ef82d3bb13e1d86912419845fa48"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.i686-w64-mingw32-cxx11.tar.gz"
[[MLX]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cfd45525b40896430436e1441509663b42a82e35"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "48e826827c6dac3d6760bbe50532a6cc4d8a05980ba6f51e081d6866ee2e0065"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc8b08f7bd3d9365f8c9ea8d3472730c279191e1"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "fbb94d53f8e5259717eb31ae327c7c75d707d4d1923ec203c6b8040e8590e6f2"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3f3f92bbf82bb7ba197078bd69aafa3a79e06792"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "a69b86036b1b70d2b6d6d4b6fad5bfabce6571952d854a1056f7e1194591d352"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.riscv64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff91d73dc6c68360bd39bb862154f547188f4bb8"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "84835edbc4cacf08c6915b2e8df25ef7f096bb51874c926cc5b95416bf0b2010"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.riscv64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
git-tree-sha1 = "66ca2143c86118e5ff41327580ea9641a9a86000"
os = "macos"

    [[MLX.download]]
    sha256 = "58e36819246d57ef61287f46326bc91cd457dc48e9fbd092e8f3f92aa03417e2"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.x86_64-apple-darwin.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eaa888b47694b50521312d7321fbc66479b780dd"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "36ffca2442490234500bdcf4372e4c6e536194a035cf5dd7c14d4ac3011922e3"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.x86_64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9d06ea051193e9cc4b1986e091c82a90568ef9c"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "266aad1f4c4e0a43200191e0dbf02e36cf77fbe7bb967fe89a868e5fac515f40"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b773613ca39fc9c8302f41d343c4fcff3b4d9800"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "7687e8e86a3355494e60002287d4705b2966c98f6bf33231e7def432f8f293ff"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.x86_64-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed07edec164dbc95ebe2e49f811efa81331a796e"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "13fdd69ea51e66ff1a45aaa49e086c62aead09d4357ae020d85f44084e9ccc41"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.x86_64-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
git-tree-sha1 = "61a1239e5c5d5e0b93304c23b8f7cad070f6a4c4"
os = "freebsd"

    [[MLX.download]]
    sha256 = "f93686b20d6508decef9a60f0ed790421118bc0da87c9295dddae19a57a64adf"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.x86_64-unknown-freebsd.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6794cc6d1e641c89bd645d6c1acf9c945007b380"
os = "windows"

    [[MLX.download]]
    sha256 = "dacf7e2a1304e0aca95a3fd509d3b8af8aaa9cee720707f30199e28cb8d6de73"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49cbb708c15c329e6d1adad125d642a60ac11215"
os = "windows"

    [[MLX.download]]
    sha256 = "8ea7a9dab82ed9fe2238a42660c85de6e48ece32c5190ee12da0f24d38bc0864"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.25.1+0/MLX.v0.25.1.x86_64-w64-mingw32-cxx11.tar.gz"
