[[MLX]]
arch = "aarch64"
git-tree-sha1 = "35007fe61f2b2b723da0f76593de65833ca37bea"
os = "macos"

    [[MLX.download]]
    sha256 = "12793c7c453276fc83b96d86f3ff19c7320339a7b2277fd2a4173c68710d1ad7"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.aarch64-apple-darwin.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2266cc73dfeda3dcdc58b9079293b789bd6380ca"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "71aa43183d4859c1fd3eccf626be3e30d15a32f292be8259f152b8d021a939af"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.aarch64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d06b0975d40bc0387ed420f505cfe2243039f50"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "3312880d8870f20c3af81804b402e7cf51625664fe75e94189f6d9849953ac7d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3e831eb3c2799baf6581c2306054da75c33ec79"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "a50a50d60737ec3ed942dc06504b51104c639c35b58495cf1de4fea4a596e16a"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.aarch64-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb8d43c554192278863cc37b17f4bf10958e4f02"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "b0cf5b3a02cd0a58c97a3b3bb430015d7386322c676f166a8f549c14b0b77f96"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.aarch64-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "aarch64"
git-tree-sha1 = "076594b33974c6b6f8997e85cab08d075d396124"
os = "freebsd"

    [[MLX.download]]
    sha256 = "4dcd8a7c89000e297fce748f51d7cb0c5163e5288bf0fa0a28f9c6e952af5073"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.aarch64-unknown-freebsd.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b822a46bd7b22a301446f92c15a1580d20e46be"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "eebb1b64424e15297088a7c5bfa9ac0120d3834c6025ffa04d68fc395497dd4d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "557db6753be83403c077fd703308b0a5927d6c93"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "10c714515fa0a497e917e3cd08f47a0df8cc88a816001f34a1744b58666744f1"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6fb2403904308d49e403a08ba4461979df73b04"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "99c7157293a8d3117927d3b37ac97be92e92f83c58e61bba7cfc0d86591f75e4"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ba05ac49afd8c62eca8cd286a5a1cf2ad503cd2"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "53c1e1922039e0483a53c59e334fc5f87ae886b8ea77722b243025fe2f37be96"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49054efe04f2fcf1bc86fd2b4a4b13682c352621"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "7b07e599d4447dfdb30006981bf97551bb961a90998efa11241cd5ee1ab71d5a"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "004d6d6280c71c4d5f379f055763d2440e4a0b37"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "6c85a055195087af0611fea634a9d821dfb68f59f576d225b899442dc25ba73d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d10d93e15262e2328d04aa750e0f2b0ad9d76bea"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "7b7877b3a3f2d5f8bff06c4d1297c11eb476abaf8eae4410174b94386b7b9ca4"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ff4163eba6372a4731783879fb49d9cd72aac07"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "f7ae690806bdc70d7fdb41eb4e364917b5e74fc0d9063f4f3139d72b9ee6ab18"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f250bf3a6cdec529e9b3652f78e9523189a97e0"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "a1fd425777c9753daad471e08d2f378d03b5af150f9cbae6ac5c21b129ed8373"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.i686-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51cf680202bb5634645a25c62561bc0273ea2776"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "2544e4ed465abda365a0e5db29dae6b513184a94dd02d29d385c8dbbca6f8966"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.i686-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23401c746ed829090ac0e863c8ccc7c4c86b2fb5"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "506ac7cd412488651d326b0660960a7411198144ecd181936e5d635214726f79"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.i686-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9247b93ee778645e07621b062c7a5061279ff47a"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "507ccfdeb3f15162ced3b786da386d6d408123eb48bdaff768d2a791b4e67356"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.i686-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a89c4a2acd7943f0dde96e1562c51ccf51780f85"
os = "windows"

    [[MLX.download]]
    sha256 = "b821610b95bac5383b83c6e90b496672894801febc00fe11d4f654365c0effd6"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.i686-w64-mingw32-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de95e8be9e16e5103d67bc24c6d6305025b9bb70"
os = "windows"

    [[MLX.download]]
    sha256 = "ee38eb1a953b3663d6919a2115c139e08d113fb29b96eff8823d86d272b1a8b6"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.i686-w64-mingw32-cxx11.tar.gz"
[[MLX]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91e4eaab8cbb246c864f37dc5c84f91c1cce68b0"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "7f5a07f22d5829642fa728aa3d48f6d17bfe735765c78931ffd4092dd9c13141"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "134cbdcd7ab815d8c56bd61783b0389e58f55700"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "0f739a427a622bdbb58076ea2d32fcd0c15a64667184543c224bab4e0f94cf02"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e45caa1888024b58505abaeba0a5707bd423d427"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "1f3a9bd037b7a4882be0144e733338783b1f72d7c31b6081baf1572b32251e1b"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.riscv64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5cdc9deeb3c49f4c01253b358afdf8ef03b94ed1"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "2ff161867849a37204f6879d4ff5c5a5fe310afbb7b14976ef9fbb02c562f659"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.riscv64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
git-tree-sha1 = "c96acb88787e02e7bf91523ee8b2da4e6dc294da"
os = "macos"

    [[MLX.download]]
    sha256 = "28f6af5ae9430a04a6ac94a5152030c91f4fc2eb45e646a2f796bbc720e944cf"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.x86_64-apple-darwin.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8241057f5a820fc8eaf9b9f68d9ccf4ac742f52"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "5eede29d5b0f4045cdd95f04104787b7077950e4d5c135eb3cd1f5e0a95f4122"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.x86_64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5dc61d68bbbc2845da666a66f5606d76761229d0"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "86ecdec7d7f530b7603da5807e00b148ba74f3498f4ab676625ef287f9d8a008"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9def41b51f64801aec3bb5ed8ab4758dc9837d66"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "495fca6aa4b41ce28c4559ac08782fb1112ccca5662e71887341a40375968729"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.x86_64-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e1e345efd48e349e87d659ad81223b4ed6ccdb5"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "43501ef6529ff8497e479f4f23f2617758c00fae0c9d2880eee71cf1a57f9964"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.x86_64-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
git-tree-sha1 = "a8e4e408b81cf98ff1ac1c75f4f64426c5df7b56"
os = "freebsd"

    [[MLX.download]]
    sha256 = "afcf597172030714f9ba562f89a1a57b7f8bb4a6e841c524062be86b69c5be12"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.x86_64-unknown-freebsd.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6976a94d95cd6f42c1ce6625c6a60aa1e5e6ce17"
os = "windows"

    [[MLX.download]]
    sha256 = "75836cbbf857d02085d0d5feab8c51e8bfbb524299a9ffb1bfa1b462c473b71b"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "717882c13956b51ea32dc4451fa38bd515025ced"
os = "windows"

    [[MLX.download]]
    sha256 = "91557e6095a4053c92692083f02f0782ae1a4d330a5e131a6be4ca06a7a96314"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.22.1+0/MLX.v0.22.1.x86_64-w64-mingw32-cxx11.tar.gz"
