[[MLX]]
arch = "aarch64"
git-tree-sha1 = "ae79d41e126a4f70d7138351cc6aba5fff3d71dd"
os = "macos"

    [[MLX.download]]
    sha256 = "2cc0f5b302381e3611bf568ae453204e396cded7f9633ae875843aa80093fafe"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.aarch64-apple-darwin.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f5dd84d548eb00573bfda84ee37c2786bedddd3"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "5ba1dbf9b1846a7a096e7fbdcd9a8ab1d85dda818f37476dfb17800d53de9b7f"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.aarch64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0f04e249df72ed84782cc41bea3ae349f6111d8"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "60c93d322157247cab59bfa4a69e3d34fde379d253943e4ead6dd8cb223777fa"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2f8dfb7bd13d0e1d59ab135ba42fabc01667ced"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "ca60c7b7ace1d7b34e385c4a2de15df1be8b48f5e889bf8c5b6525bb20cfa57f"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.aarch64-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3644534006b7381673d6e80abcda1ad3d0d3cc0b"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "10744b2035150ca4dde1d2a6b1b635182106c1f64eb439988d90012535087e77"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.aarch64-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "aarch64"
git-tree-sha1 = "eafae2a99deed1909209d4626e49d5d25c08a9f5"
os = "freebsd"

    [[MLX.download]]
    sha256 = "e96d66f66092cf34200f9bde5399ca29efb049ae8632901b2617d89cee9fd90e"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.aarch64-unknown-freebsd.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6201b0c058c1bab48923f9194d96e2eddc4d7e6"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "dd3c2c6b7cb0b3a3004d6e77802ebc0e0cccb8350dc5f45dd7a6a6aeed627a60"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7793c9e4c3f9609436bbe1fa2afc8b4b304d9b9c"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "f85fa635e9d844725c4d8c208030a15b0d1722b92a9aa9db1200d7794cc488fb"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae4bc89b530e222f1056934925af36810379d46c"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "5da7e03ce12ab7e6f6d473aa6c45b8e369f1c46e0c4c4309d00c789c5cc31523"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5219f7c4a29e3b2d17f2faf03c0b17a7645be0d1"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "46844562ba2f35a17933206722f2c687d7f2be456b39549f113cd7fb9d7d9325"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7121e5d927d876bc47d5b1862f373669c5f441c"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "50a24f578bfba093bdbe82cd46272c4bb25bd3254c8b284ad8bf3d0e12a0eb71"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8dd730e05cac5faa8698c3dfbf72130bd54bc62a"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "856bf57e7000954abcb255196b77dc3d334ad992536552fafeb8479bdfe33ba1"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ff42a2f3a7cf812e5d8b5c04ff39ab8d7f01944"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "492d699e7515e3f6a291edda5edff0a29c43abfff8dc94824ae241718aac6e90"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff848317505839fe6a9a71421eb70e8b575918c7"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "ec94db0b899bf09c3f20d850dc81dbda58deb361c1106f64a95bb44b359af9c7"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3d82b17150e7bde01e58931ea79cb4a088e3440"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "c9564035891e38e3f4a603d7f662dc2be710aed1a4ad7ad8189142e518795e5f"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.i686-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b821892a24651b7f7ff66fb8c86a1e7ec4fb6ad"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "03c11aec5597f8bcf90c36b7e46992940abc1f939225ceafa8a58a56b36600f0"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.i686-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b15c09bf8b8cee4e4b6a23f4addf23cb40370633"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "21db902591f9f1f7304b9c9c52e21e159b31f4be430683dc37ed276c2289e67f"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.i686-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0dc7e0f47ad62c3a66257fcf48b046d90cb71eab"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "6a430620851c8a621dd27365a07fee915202c7bc66f8359e4d35acdf7b2e851f"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.i686-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "24bb1d6efa7581463f58fd59ebeccbcbd6621f45"
os = "windows"

    [[MLX.download]]
    sha256 = "5f8d341cf318a32fab59a93fe70e53a51c8ff9671c886998ffe786718653c306"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.i686-w64-mingw32-cxx03.tar.gz"
[[MLX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41d13a9c8f0956f5db2581a0fe0ef21753525f5f"
os = "windows"

    [[MLX.download]]
    sha256 = "d04ca98d1c6280340f4f2900a2083aa51e87b0f22b62cea9f988cb62971a2a3d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.i686-w64-mingw32-cxx11.tar.gz"
[[MLX]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e8c9dfda1b97a0d8f668e5005293f71d9ba3395"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "7a171b85f0d20bc81593f415e7a696d4495c384b01664924142047254e639fdb"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6b1b00fc386613af98b21281324ce8fc9671080"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "b2022e6877c3f7c2ae25db9ff615d70a03812e902fe63f69afa18b037ad6fef0"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59350119ca5e2b91666ae20621487adfb1484a24"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "06ea93a48dbac3d925369c46d909b3fd3954edca4a6f1e286c8ddb2d2f6ebc04"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.riscv64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1750bd0510b857e5ae1beaab23cd6ca6876f3227"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "2690a5a3ace3a9282f46c5bc635412a1991d1f7234e60ff29820f22f7345e352"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.riscv64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
git-tree-sha1 = "f3afd80701cecd694517a37c705d5c50be36607c"
os = "macos"

    [[MLX.download]]
    sha256 = "3c2f4b141631f6a6a09a6885674416559ea5c7986e4a512ae2cd7dc7eb61bcb5"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.x86_64-apple-darwin.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d09f41f94ca248b03b8f28a84af6d2e6290b75e4"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "18648a3ef390cd60d1dda1570b6ea57a6901e3c25d06b48b3dd052531334d52a"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.x86_64-linux-gnu-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5884ae35a1d2c040fc200d2303f66ad3f339f482"
libc = "glibc"
os = "linux"

    [[MLX.download]]
    sha256 = "b2e343da87556704fe51a1943ca891d7610bbbfbb522148de36975c70651e61d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "577df26088a47ff9acfdd6176df8ab04605289a1"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "269eb7e43e335619c23c809a488380c183f84865b3966557f8d5d8e24f47d2ad"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.x86_64-linux-musl-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "011304216621d37159c96619589bca2c70abaf1d"
libc = "musl"
os = "linux"

    [[MLX.download]]
    sha256 = "73b8425df3f783a060589cd9e484d010a4e16a961e58c02b633f669ea8a206d9"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.x86_64-linux-musl-cxx11.tar.gz"
[[MLX]]
arch = "x86_64"
git-tree-sha1 = "cba9489d933f28fed26c0c802e74fa5d314e4137"
os = "freebsd"

    [[MLX.download]]
    sha256 = "9e71d3eca02389abf3fb34a6fdf1479ab5665978083cde5bb174da6547d2a41d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.x86_64-unknown-freebsd.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0bbb6b721ee76668ec0df6d057b6b3f515144c5"
os = "windows"

    [[MLX.download]]
    sha256 = "408da2bc48af98b2336f5b2edd1164c7d793182ff1d0948c50c8ba02004b812c"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8b7cee89032b454bfc4079f64213ba4c23a5307"
os = "windows"

    [[MLX.download]]
    sha256 = "5f8fa50e3c69405c4f60352c26c362edadf29e52b9794a4bd2d1fc4bdf39f2b6"
    url = "https://github.com/JuliaBinaryWrappers/MLX_jll.jl/releases/download/MLX-v0.23.1+0/MLX.v0.23.1.x86_64-w64-mingw32-cxx11.tar.gz"
